# Generated by Django 2.2.5 on 2020-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('address', models.EmailField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'User',
                'ordering': ['user_id'],
            },
        ),
    ]
