# Generated by Django 2.2.5 on 2020-01-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='email',
        ),
    ]
