# Generated by Django 2.2.5 on 2020-02-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0004_auto_20200209_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user_id',
            new_name='username',
        ),
    ]
