# Generated by Django 2.2.5 on 2020-02-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0005_auto_20200209_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=100)),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revision_application.Folder')),
            ],
            options={
                'db_table': 'Set',
                'ordering': ['set_id'],
            },
        ),
    ]
