# Generated by Django 2.2.5 on 2020-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0006_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='folder_name',
            new_name='folder_id',
        ),
    ]
