# Generated by Django 2.2.5 on 2020-02-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0007_auto_20200209_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='folder_id',
            field=models.ForeignKey(db_column='folder_id', on_delete=django.db.models.deletion.CASCADE, to='revision_application.Folder'),
        ),
    ]
