# Generated by Django 2.2.5 on 2020-02-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0008_auto_20200210_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='revision_application.User'),
        ),
    ]
