# Generated by Django 2.2.5 on 2020-02-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision_application', '0009_auto_20200210_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1500, null=True)),
                ('level', models.IntegerField(default=1)),
                ('set_id', models.ForeignKey(db_column='set_id', on_delete=django.db.models.deletion.CASCADE, to='revision_application.Set')),
            ],
            options={
                'db_table': 'Question',
                'ordering': ['question_id'],
            },
        ),
    ]
